server:
	PYTHONPATH=../../../../autobahn python server.py

server_with_timeservice:
	PYTHONPATH=../../../../autobahn python server.py --component "timeservice.TimeServiceBackend"

client_timeservice_frontend:
	PYTHONPATH=../../../../autobahn python client.py --component "timeservice.TimeServiceFrontend"

client_timeservice_backend:
	PYTHONPATH=../../../../autobahn python client.py --component "timeservice.TimeServiceBackend"
