server1_asyncio:
	PYTHONPATH=../../autobahn python3 server.py asyncio

server1_twisted:
	PYTHONPATH=../../autobahn python server.py twisted

client1_asyncio:
	PYTHONPATH=../../autobahn python3 client.py
