server1_asyncio:
	PYTHONPATH=../../autobahn python3 server_asyncio.py

server1_twisted:
	PYTHONPATH=../../autobahn python server_twisted.py

client1_asyncio:
	PYTHONPATH=../../autobahn python3 client.py
