server:
	PYTHONPATH=../../../../autobahn python3 server.py

client:
	PYTHONPATH=../../../../autobahn python3 client.py

client_coroutines:
	PYTHONPATH=../../../../autobahn python3 client_coroutines.py
