# .readthedocs.yaml
# Read the Docs configuration file for autobahn
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  # Install system packages for spell checking
  apt_packages:
    - libenchant-2-2

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    # Install the package with docs dependencies
    - method: pip
      path: .
      extra_requirements:
        - docs
