connect:
	python test_connect.py --gateway http://localhost:1545

transfer:
	python test_transfer_tokens.py --gateway http://localhost:1545

register:
	python test_register.py --gateway http://localhost:1545

market:
	python test_market.py --gateway http://localhost:1545

payment_channel:
	python test_payment_channel.py --gateway http://localhost:1545
