# {'attrs': {},
#  'bytesize': 0,
#  'docs': '',
#  'fields': {'address': {'attrs': {'ethadr': '0'},
#                         'default_int': 0,
#                         'default_real': 0.0,
#                         'deprecated': False,
#                         'docs': 'Primary Ethereum address of the device '
#                                 'vendor.',
#                         'id': 5,
#                         'name': 'address',
#                         'offset': 14,
#                         'required': False,
#                         'type': {'basetype': 'Vector',
#                                  'element': 'UByte',
#                                  'index': -1}},
#             'created': {'attrs': {'readonly': '0', 'timestamp': '0'},
#                         'default_int': 0,
#                         'default_real': 0.0,
#                         'deprecated': False,
#                         'docs': 'Point in time (UTC) when vendor created, in '
#                                 'Unix time (ns precision).',
#                         'id': 2,
#                         'name': 'created',
#                         'offset': 8,
#                         'required': False,
#                         'type': {'basetype': 'ULong',
#                                  'element': 'None',
#                                  'index': -1}},
#             'modified': {'attrs': {'readonly': '0', 'timestamp': '0'},
#                          'default_int': 0,
#                          'default_real': 0.0,
#                          'deprecated': False,
#                          'docs': 'Point in time (UTC) when vendor was last '
#                                  'modified, in Unix time (ns precision).',
#                          'id': 3,
#                          'name': 'modified',
#                          'offset': 10,
#                          'required': False,
#                          'type': {'basetype': 'ULong',
#                                   'element': 'None',
#                                   'index': -1}},
#             'name': {'attrs': {},
#                      'default_int': 0,
#                      'default_real': 0.0,
#                      'deprecated': False,
#                      'docs': 'Display name of the vendor (must be unique for '
#                              'all vendors).',
#                      'id': 4,
#                      'name': 'name',
#                      'offset': 12,
#                      'required': False,
#                      'type': {'basetype': 'String',
#                               'element': 'None',
#                               'index': -1}},
#             'ocn': {'attrs': {},
#                     'default_int': 0,
#                     'default_real': 0.0,
#                     'deprecated': False,
#                     'docs': 'Object logical change number.',
#                     'id': 1,
#                     'name': 'ocn',
#                     'offset': 6,
#                     'required': False,
#                     'type': {'basetype': 'UInt',
#                              'element': 'None',
#                              'index': -1}},
#             'oid': {'attrs': {'readonly': '0', 'uuid': '0'},
#                     'default_int': 0,
#                     'default_real': 0.0,
#                     'deprecated': False,
#                     'docs': 'Object ID.',
#                     'id': 0,
#                     'name': 'oid',
#                     'offset': 4,
#                     'required': False,
#                     'type': {'basetype': 'Vector',
#                              'element': 'UByte',
#                              'index': -1}}},
#  'is_struct': False,
#  'min_align': 1,
#  'name': 'com.things.home.device.HomeDeviceVendor'}
